### ISSUE TITLE
How can I get product special price data?

### ISSUE THREAD

**Issue by jeroencusters** [grayloon/magento-laravel-api#56]
Hi, great wrapper!

I don't know how to load special prices for product

https://devdocs.magento.com/guides/v2.4/rest/modules/catalog-pricing.html#get-special-prices

I tried custom modules option (https://github.com/grayloon/magento-laravel-api#custom-modules), but I get the following error: Call to protected method Grayloon\Magento\Api\AbstractApi::post() from context 'App\Http\Controllers\WebhookController'

Thanks in advance for help!

**Comment by ahinkle** [comment]
Hi, @jeroencusters

We don't currently offer that endpoint but since that is a native Magento API feature, we are welcome to PRs.

In it's current state, to retrieve special prices, it would look something like this:

```php

$magento->api('products/special-price-information')->post('', [
  "skus" => [
        "24-WB06",
        "240-LV06",
        "24-WG080",
  ],
]);

```

I understand this isn't very intuitive with the extra `post('', [..` as we are already using  `products()` API.  I'll work on this soon but otherwise, feel free to open a PR for the endpoint within `products()` so it would be a bit cleaner.

would end up looking a lot cleaner by doing something like: 
```php
$magento->api('products')->specialPriceInformation([
        "24-WB06",
        "240-LV06",
        "24-WG080",
]);
```

**Comment by jeroencusters** [comment]
@ahinkle thanks for your help. This call with the extra post will do for now. I will only use this for individual SKU together with $magento->api('products')->show($sku) since the special price custom_attribute of product doesn't show the validity dates.

**Comment by ahinkle** [comment]
Closing for now as the product show should be able to get the data you have. Let me know if you still need it
