### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by ahinkle** [grayloon/magento-laravel-api#93]
Hi everyone,

We have discontinued working with Magento in favor of other platforms. We are looking for maintainers to take over this package. 

Interested? Drop a comment here or email me at ahinkle@grayloon.com.

Thanks!

**Comment by ahinkle** [comment]
I received a few emails with minimal detail other than wishing to maintain the package. 

Please provide _how_ you wish to contribute and maintain the project.

Thanks!

**Comment by ramonrietdijk** [comment]
Hi @ahinkle,

First of all, thank you for creating this package and your contributing to the OS community.

We have used your package in a lot of our projects and have made a few contributions as well.

The approach of creating a class for each Magento endpoint seems like a neat idea as you can easily see what is available to you. It unfortunately brings a lot of work too in order to create and maintain these classes.

That's why we have created a [package](https://github.com/justbetter/laravel-magento-client) with a more minimalistic approach in which the client can be used to make requests directly. This is especially helpful with a lot of custom endpoints. Although we do have some predefined classes, it is primarily to overcome rewriting the same code repeatedly and being able to fetch results lazily.

If you do not wish to maintain the package anymore, ours could be a replacement. We would be happy to write a migration guide. Luckily, the environmental variables are already compatible with each other.

**Comment by ahinkle** [comment]
Hi @ramonrietdijk ,

We have marked the package replacement as `justbetter/laravel-magento-client`. Thanks so much!
